// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCam14gp9vULeKD-Twf6Qyat114XA1ONwY',
    appId: '1:593508116669:web:ad4b6f8e08cea3e653efd4',
    messagingSenderId: '593508116669',
    projectId: 'swiftmanagerpro',
    authDomain: 'swiftmanagerpro.firebaseapp.com',
    storageBucket: 'swiftmanagerpro.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl4P3Wy2isk-pMYEUaxq-I-RBimHZdyiI',
    appId: '1:593508116669:android:20c81870beb1785353efd4',
    messagingSenderId: '593508116669',
    projectId: 'swiftmanagerpro',
    storageBucket: 'swiftmanagerpro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsJeoY_zfL5yIgIr6Sdx4L6wuzBB6fQjE',
    appId: '1:593508116669:ios:ea555a24a8c19be153efd4',
    messagingSenderId: '593508116669',
    projectId: 'swiftmanagerpro',
    storageBucket: 'swiftmanagerpro.appspot.com',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsJeoY_zfL5yIgIr6Sdx4L6wuzBB6fQjE',
    appId: '1:593508116669:ios:af37dc73f9fc0b3953efd4',
    messagingSenderId: '593508116669',
    projectId: 'swiftmanagerpro',
    storageBucket: 'swiftmanagerpro.appspot.com',
    iosBundleId: 'com.example.quizapp.RunnerTests',
  );
}
